-- Auto-generated by migrate-lesson-data-to-postgres.mjs
BEGIN;

INSERT INTO organizations (slug, name) VALUES ('default-org', 'Default Organization') ON CONFLICT (slug) DO NOTHING;
INSERT INTO courses (org_id, slug, default_locale, is_published)
  SELECT id, 'cooking-basics', 'th', true FROM organizations WHERE slug = 'default-org'
  ON CONFLICT (org_id, slug) DO NOTHING;

INSERT INTO course_translations (course_id, locale, title, subtitle)
  SELECT c.id, 'th', 'ระบบบทเรียนออนไลน์ การประกอบอาหารเบื้องต้น', 'เริ่มจากแบบทดสอบก่อนเรียน จากนั้นรออาจารย์เปิดบทเรียนเพื่อเรียนเนื้อหาและทำแบบทดสอบหลังเรียน'
  FROM courses c JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics'
  ON CONFLICT (course_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

INSERT INTO course_modules (course_id, sort_order, slug)
  SELECT c.id, 1, 'main' FROM courses c JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics'
  ON CONFLICT (course_id, slug) DO NOTHING;

INSERT INTO classrooms (course_id, org_id, slug, name)
  SELECT c.id, o.id, 'cooking-basics', 'ห้องเรียนทั่วไป'
  FROM courses c JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics'
  ON CONFLICT (course_id, slug) DO NOTHING;

-- Page 1: home
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 1, 1, 'home', NULL, '{}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'ระบบบทเรียนออนไลน์ การประกอบอาหารเบื้องต้น', 'เริ่มจากแบบทดสอบก่อนเรียน จากนั้นรออาจารย์เปิดบทเรียนเพื่อเรียนเนื้อหาและทำแบบทดสอบหลังเรียน', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 2: quiz-interactive
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 2, 2, 'quiz_interactive', 'pre', '{"pass_threshold":0.6}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'แบบทดสอบก่อนเรียน (Pre-Test)', 'ดูรูปประกอบแล้วตอบคำถามง่าย ๆ 10 ข้อ — ใช้วัดความรู้เบื้องต้นก่อนเรียน ไม่ต้องกังวลหากยังตอบไม่ได้', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 1, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'จากรูปนี้ ข้อใดอธิบาย “การประกอบอาหาร” ได้ใกล้เคียงที่สุด?', 'สังเกตจากภาพ: มีการเตรียมวัตถุดิบและปรุงอาหารให้พร้อมรับประทาน', 'https://images.unsplash.com/photo-1495521821757-a1efb6729352?auto=format&fit=crop&w=640&q=75&fm=webp', 'เชฟกำลังเตรียมผักและวัตถุดิบสดในครัว' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 1
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'จัดจานให้สวยอย่างเดียว' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 1
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'นำวัตถุดิบมาเตรียมและปรุงให้เหมาะกับการรับประทาน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 1
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'เก็บอาหารดิบไว้นานที่สุดโดยไม่ใช้ความร้อน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 1
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'เลือกซื้อของจากตลาดเท่านั้น' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 2, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'จากรูป ทำไมเราจึงควรปรุงอาหารให้สุกด้วยความร้อน?', 'ลองคิดถึงความปลอดภัยเมื่อรับประทานอาหาร', 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=640&q=75&fm=webp', 'อาหารกำลังถูกปรุงบนเตาให้สุก' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 2
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'เพื่อให้อาหารหนักขึ้น' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 2
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'เพื่อช่วยทำลายเชื้อโรคและทำให้ปลอดภัยขึ้น' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 2
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'เพื่อให้ทุกอย่างมีรสหวาน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 2
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'เพื่อให้เก็บได้ตลอดไปโดยไม่เสีย' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 3, 2 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'งานแบบในรูป (อาหารร้อน ย่าง ทอด อบ) มักอยู่ในครัวประเภทใด?', 'ครัวที่เน้นอาหารร้อนและใช้ความร้อนสูง', 'https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=640&q=75&fm=webp', 'ครัวร้อนกำลังปรุงอาหารบนเตา' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 3
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวเย็น' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 3
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวเบเกอรี่' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 3
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวร้อน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 3
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวเครื่องดื่ม' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 4, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'จากรูป งานประเภทสลัดและอาหารเย็นมักอยู่ในครัวใด?', 'ครัวที่เน้นความสดและควบคุมอุณหภูมิให้เย็น', 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=640&q=75&fm=webp', 'สลัดผักสดจัดเสิร์ฟแบบเย็น' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 4
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวร้อน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 4
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวเย็น' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 4
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวเบเกอรี่' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 4
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวซุป' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 5, 2 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'จากรูป งานเบเกอรี่เน้นเรื่องใดเป็นพิเศษ?', 'สังเกตการชั่งตวงและความละเอียดของขั้นตอน', 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=640&q=75&fm=webp', 'ขนมปังและของอบในครัวเบเกอรี่' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 5
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ไม่ต้องชั่งตวงส่วนผสม' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 5
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ใช้สายตากะปริมาณอย่างเดียว' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 5
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ต้องชั่งตวงแม่นยำและควบคุมขั้นตอน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 5
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'เสิร์ฟแบบเย็นเท่านั้น' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 6, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'วิธีปรุงในรูป (ปิ้ง/ย่าง) จัดอยู่ในกลุ่มความร้อนแบบใด?', 'อาหารสัมผัสความร้อนโดยไม่จมในน้ำ', 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=640&q=75&fm=webp', 'อาหารกำลังถูกปิ้งบนตะแกรง' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 6
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ความร้อนชื้น (นึ่ง/ต้ม)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 6
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ความร้อนแห้ง (ปิ้ง/ย่าง/อบ)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 6
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ใช้น้ำมัน (ทอด)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 6
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ไม่ใช้ความร้อน' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 7, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'วิธีปรุงในรูป (นึ่ง) จัดอยู่ในกลุ่มความร้อนแบบใด?', 'ใช้ไอน้ำจากน้ำเดือด ไม่ต้มจมในน้ำ', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=640&q=75&fm=webp', 'อาหารนึ่งในหม้อนึ่ง' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 7
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ความร้อนแห้ง' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 7
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ความร้อนชื้น' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 7
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ใช้น้ำมันมาก' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 7
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การแช่แข็ง' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 8, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'หลังลวกผักในน้ำเดือดแล้ว ควรทำอย่างไรตามรูป?', 'เพื่อหยุดความร้อนและคงสีสดของผัก', 'https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=640&q=75&fm=webp', 'ผักสดที่เตรียมลวก' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 8
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'พักไว้กลางแดด' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 8
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'แช่น้ำเย็นทันทีเพื่อหยุดความร้อน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 8
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'นำไปทอดต่อทันที' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 8
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ปิดฝาทิ้งไว้ในหม้อ' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 9, 0 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'จากรูป ข้อควรระวังเมื่อทอดอาหารคืออะไร?', 'อาหารอาจดูน่ารับประทาน แต่มีสิ่งหนึ่งที่มักมากเกินไป', 'https://images.unsplash.com/photo-1569691899455-88464f6d3ab1?auto=format&fit=crop&w=640&q=75&fm=webp', 'อาหารทอดกรอบในน้ำมันร้อน' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 9
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'อาหารอาจอมน้ำมันมากเกินไป' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 9
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'อาหารจะไม่มีวันสุก' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 9
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'อาหารจะไม่มีสีและกลิ่น' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 9
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'อาหารจะเย็นทันที' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 2 AND lp.sort_order = 2
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 10, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'ทำไมการนึ่งแบบในรูปจึงช่วยสงวนคุณค่าอาหารได้ดี?', 'สารอาหารไม่ได้ละลายไปกับน้ำโดยตรง', 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=640&q=75&fm=webp', 'หม้อนึ่งและไอน้ำจากการปรุงอาหาร' FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 10
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'อาหารจมในน้ำตลอดเวลา' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 10
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'สารอาหารไม่ละลายทิ้งไปกับน้ำต้มโดยตรง' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 10
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ต้องใช้น้ำมันมาก' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 2 AND qq.sort_order = 10
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ใช้ไฟแรงจนไหม้เสมอ' FROM inserted_o;

-- Page 3: cover
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 3, 3, 'cover', NULL, '{"author":"รวบรวมโดย: อ. กฤดิทร สุขกมล","course":"รายวิชา: การประกอบอาหารเบื้องต้น","details":"หมวดวิชาคหกรรมศาสตร์ แผนกอาหารและโภชนาการ\nเอกสารประกอบการสอนฉบับมาตรฐาน\nภาคเรียนที่ 1 ปีการศึกษา 2569","image":"[https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1600&q=80&fm=webp](https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?auto=format&fit=crop&w=1600&q=80&fm=webp)"}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'ความรู้เบื้องต้นเกี่ยวกับการประกอบอาหาร', 'เอกสารประกอบการเรียนเชิงวิชาการ / E-Learning Module (หลักสูตร 4 ชั่วโมง)', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 4: article
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 4, 4, 'article', NULL, '{"image":"[https://images.unsplash.com/photo-1495521821757-a1efb6729352?auto=format&fit=crop&w=800&q=80&fm=webp](https://images.unsplash.com/photo-1495521821757-a1efb6729352?auto=format&fit=crop&w=800&q=80&fm=webp)","sections":[{"subtitle":"การประกอบอาหารคืออะไร?","content":"การประกอบอาหาร หมายถึงกระบวนการนำวัตถุดิบและอาหารดิบมาทำให้สุกด้วยความร้อน เพื่อทำให้อาหารมีคุณสมบัติที่เหมาะสมและมีคุณค่าแก่การบริโภค กระบวนการนี้ไม่ได้มีแค่การตั้งไฟ แต่ครอบคลุมตั้งแต่กระบวนการคัดเลือกวัตถุดิบที่สดใหม่ การล้างทำความสะอาด การหั่นเตรียม (Mise en place) การปรุงด้วยเทคนิคความร้อนที่เหมาะสม การจัดเสิร์ฟที่สวยงาม และการเก็บรักษาอย่างถูกวิธี"},{"subtitle":"องค์ประกอบแห่งความสำเร็จ","content":"การประกอบอาหารที่ดีจะต้องคำนึงถึง \"ความสะอาดและถูกสุขลักษณะ\" เป็นหัวใจสำคัญสูงสุด องค์ประกอบที่สำคัญเริ่มต้นตั้งแต่ตัว \"ผู้ประกอบอาหาร\" ที่ต้องมีสุขอนามัยที่ดี อุปกรณ์ที่ใช้ต้องสะอาด ตำรับอาหารต้องได้มาตรฐาน เครื่องปรุงต้องช่วยส่งเสริมคุณค่า รสชาติ กลิ่น และเนื้อสัมผัสที่ดี รวมไปถึงศิลปะและทักษะในการประกอบอาหาร รูปแบบการเสิร์ฟ ภาชนะบรรจุ และการคำนวณช่วงเวลาในการเสิร์ฟที่แม่นยำ"},{"subtitle":"ผลลัพธ์ที่ได้จากการประกอบอาหาร","content":"อาหารที่ผ่านการปรุงสุกอย่างถูกต้องตามหลักวิชาการ เมื่อรับประทานเข้าไปแล้วจะมีประโยชน์สูงสุดต่อร่างกาย ทำให้ร่างกายเจริญเติบโต ซ่อมแซมส่วนที่สึกหรอ ส่งผลดีต่อทั้งสุขภาพกาย (ปราศจากโรคภัย) และสุขภาพใจ (ความสุขจากการได้รับประทานอาหารที่รสชาติดี)"}]}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'ความหมายของการประกอบอาหาร', '', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 5: cards-grid
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 5, 5, 'cards_grid', NULL, '{"items":[{"icon":"ShieldCheck","title":"1. ทำให้อาหารสุก สะอาด ปราศจากเชื้อโรค","desc":"อาหารที่สุกด้วยการปรุงผ่านความร้อนสูงและเป็นเวลานานพอสมควร ทำให้แน่ใจได้ว่าแบคทีเรีย เชื้อโรค และพยาธิที่แฝงมากับวัตถุดิบถูกทำลายไปแล้ว จึงจะสะอาดเพียงพอสำหรับการรับประทานอย่างปลอดภัย ถูกสุขลักษณะ"},{"icon":"HeartPulse","title":"2. สงวนคุณค่าทางโภชนาการ","desc":"แม้ความร้อนจะทำลายสารอาหารบางชนิด โดยเฉพาะ \"วิตามินที่ละลายน้ำได้ เช่น วิตามิน B และ C\" แต่การเลือกเทคนิคที่ถูกต้อง (เช่น การนึ่งแทนการต้มน้ำทิ้ง) จะช่วยสงวนคุณค่าทางอาหารไว้ให้ร่างกายดูดซึมได้มากที่สุด"},{"icon":"Sparkles","title":"3. ทำให้อาหารย่อยง่ายขึ้น","desc":"ความร้อนทำให้โปรตีนในเนื้อสัตว์คลายตัวและแป้งสุกตัว เครื่องปรุงรสที่ใช้มีผลโดยตรงต่อความนุ่มของเนื้อสัมผัส ทำให้กระเพาะอาหารและลำไส้ของเราทำงานเบาลงและย่อยได้ง่ายขึ้น"},{"icon":"Flame","title":"4. รสชาติและกลิ่นดีขึ้น (เกิดปฏิกิริยาเคมี)","desc":"ความร้อนก่อให้เกิดปฏิกิริยา Maillard (การเกิดสีน้ำตาลและกลิ่นหอม) ทำให้อาหารมีการเปลี่ยนแปลงทางเคมี ส่งผลให้รสชาติ กลิ่น และสีสันเปลี่ยนไปในทางที่ดีขึ้น กระตุ้นความอยากอาหาร"},{"icon":"Timer","title":"5. ป้องกันการเน่าเสีย เก็บได้นานขึ้น","desc":"เอนไซม์และแบคทีเรียคือตัวการสำคัญที่ทำให้อาหารเน่าเสีย ความร้อนจากการประกอบอาหารจะช่วยยับยั้งและทำลายการทำงานของพวกมัน ช่วยยืดอายุการเก็บรักษาอาหารได้นานขึ้น"}]}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'ประโยชน์ 5 ประการของการประกอบอาหาร', 'เจาะลึกเหตุผลสำคัญทางวิทยาศาสตร์และโภชนาการที่เราต้องนำอาหารมาปรุงสุก', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 6: split-advanced
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 6, 6, 'split_advanced', NULL, '{"highlight":"ศูนย์กลางการปรุงสุกและการควบคุมอุณหภูมิความร้อน","content":"ครัวร้อนเป็นหัวใจหลักของร้านอาหาร รับผิดชอบการปรุงอาหารที่เสิร์ฟในลักษณะอาหารร้อน เช่น อาหารอบ ทอด ปิ้ง ย่าง เมนูจานหลัก (Main Course) งานในส่วนนี้มีความกดดันสูง ต้องทำงานแข่งกับเวลา ดูแลการผลิตอาหารให้มีการสิ้นเปลืองและเน่าเสียน้อยที่สุด ควบคุมปริมาณ รสชาติ และอุณหภูมิให้ได้มาตรฐานขณะส่งถึงมือลูกค้า","departments":["Soup & Stock (แผนกซุปและเคี่ยวน้ำสต็อกพื้นฐาน)","Meat & Seafood (แผนกจัดการเนื้อสัตว์และอาหารทะเลสด)","Vegetable & Starch (แผนกผักสดและคาร์โบไฮเดรต/มันฝรั่ง/พาสต้า)","Sauce (แผนกปรุงซอสร้อนที่เป็นหัวใจของรสชาติ)","Breakfast & Chip (แผนกอาหารเช้าและของทอด)"],"image":"[https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80&fm=webp](https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=800&q=80&fm=webp)"}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'ครัวร้อน (Hot Kitchen)', '', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 7: split-advanced
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 7, 7, 'split_advanced', NULL, '{"highlight":"ศิลปะแห่งความสดใหม่ การจัดแต่ง และการควบคุมอุณหภูมิ","content":"ครัวเย็นรับผิดชอบการปรุงและตกแต่งอาหารที่ไม่ต้องใช้ความร้อนในขั้นตอนสุดท้าย เช่น เมนูเรียกน้ำย่อย (Appetizer) อาหารประเภทเนื้อปรุงสุกเสิร์ฟเย็น (Cold Cut) เช่น แฮม ไส้กรอก ชีสบอร์ด การจัดเตรียมครัวเย็นต้องเน้นเรื่องสุขอนามัยขั้นสูงสุด และต้องควบคุมอุณหภูมิในห้องให้เย็นเสมอเพื่อป้องกันการเติบโตของแบคทีเรีย","departments":["Butcher (แผนกชำแหละ ตัดแต่ง และเตรียมเนื้อสัตว์/ปลาสด)","Sandwich & Canape (แผนกประกอบแซนด์วิชและคานาเป้ชิ้นพอดีคำ)","Cold Sauce & Dressing (แผนกทำซอสเย็น มายองเนส และน้ำสลัด)","Cold Cut (แผนกสไลด์เนื้อปรุงสุกเสิร์ฟเย็นและชีส)","Various Salads & Vegetable (แผนกสลัดและจัดเตรียมผักสด)"],"image":"[https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80&fm=webp](https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80&fm=webp)"}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'ครัวเย็น (Cold Kitchen / Garde Manger)', '', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 8: split-advanced
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 8, 8, 'split_advanced', NULL, '{"highlight":"ความแม่นยำ วิทยาศาสตร์ และศิลปะในการอบขนม","content":"เป็นครัวที่รับผิดชอบในการทำขนมอบ ขนมปัง ขนมเค้ก คุกกี้ พาย งานด้านเบเกอรี่คือวิทยาศาสตร์ที่ต้องใช้การชั่งตวงที่แม่นยำ 100% (Scaling) หน้าที่ของบุคลากรนอกจากจะต้องผลิตแล้ว ยังต้องดูแลให้ขนมทุกอย่างมีปริมาตร เนื้อสัมผัส และอุณหภูมิที่เหมาะสม จัดตกแต่งสำหรับโอกาสพิเศษต่างๆ ให้สวยงาม","departments":["Pastry (เพสตรี้/ขนมอบประดิษฐ์สไตล์ฝรั่งเศส ทาร์ต เอแคลร์)","Bakery (เบเกอรี่/ขนมปัง ยีสต์ โดว์)","Frozen Dessert (ของหวานแช่แข็ง/ไอศกรีม/ซอร์เบต์)","Cold Dessert (ของหวานเสิร์ฟเย็น/พานาคอตต้า/มูส)"],"image":"[https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80&fm=webp](https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=80&fm=webp)"}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'ครัวเบเกอรี่ (Bakery & Pastry Kitchen)', '', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 9: methods
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 9, 9, 'methods', NULL, '{"items":[{"name":"1. การปิ้ง (Grill)","desc":"การนำอาหารวางลงบนตะแกรงเหล็กเหนือเตาถ่านที่มีความร้อนไม่มาก ปิ้งกลับไปมาในเวลาสั้นๆ ใช้ได้ทั้งอาหารสดและแห้ง ช่วยให้อาหารมีกลิ่นควันอ่อนๆ","image":"[https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"2. การย่าง (Roast / BBQ)","desc":"คล้ายการปิ้งแต่ใช้เวลานานกว่าและชิ้นเนื้อใหญ่กว่า เพื่อให้อาหารสุกระอุทั่วถึงกัน มักทาน้ำมันหรือห่อใบตองเพื่อกันไหม้และเพิ่มกลิ่นหอม ย่างข้างละ 2 นาทีแล้วพลิก","image":"[https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"3. การเผา (Burn)","desc":"ทำให้อาหารสุกโดยใช้ไฟแรง วางของที่จะเผาลงบนไฟโดยตรงหรือสัมผัสความร้อนใกล้ชิด พลิกกลับไปมาให้สุกทั้งด้านนอกและด้านใน","image":"[https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"4. การอบ (Bake / Roast in Oven)","desc":"ใช้อากาศร้อนหมุนเวียนจากเตาอบ (เช่น อุณหภูมิ 190 องศาฯ สำหรับไก่อบ ใช้เวลา 20-30 นาที) ต้องอุ่นเตาอบให้ร้อนก่อนเสมอ (Pre-heat 15 นาที)","image":"[https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80&fm=webp)"}],"pros":"ข้อดี: เป็นวิธีการประกอบอาหารที่ช่วย \"สงวนคุณค่าทางโภชนาการ\" ไว้ได้มาก ผิวอาหารจะหอม มีสีเข้มสวยงาม (Maillard reaction) และดูน่ารับประทาน","cons":"ข้อเสีย: หากใช้เวลาในการทำนานเกินไป จะทำให้อาหารสูญเสียน้ำ แห้งกระด้างเกินไป ดูไม่น่ารับประทานและเสียรสชาติ"}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'เทคนิคการประกอบอาหารด้วยความร้อนแห้ง', 'การปิ้ง ย่าง เผา อบ (Dry Heat Cooking Methods)', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 10: methods
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 10, 10, 'methods', NULL, '{"items":[{"name":"5. การต้ม (Boil)","desc":"ใส่อาหารในน้ำเดือด (100°C) จนสุก เหมาะสำหรับเคี่ยวเนื้อสัตว์ให้เปื่อย (ข้อเสีย: วิตามินที่ละลายน้ำได้ เช่น B และ C มักละลายทิ้งไปกับน้ำต้ม)","image":"[https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"6. การลวก (Blanch)","desc":"ทำให้อาหารกึ่งสุกกึ่งดิบในน้ำเดือดจัดระยะสั้นๆ แล้ว \"แช่น้ำเย็นทันที\" เพื่อหยุดความร้อน ช่วยสงวนวิตามินและสีสันของผัก (ไม่เหมาะกับผักเนื้อแข็ง)","image":"[https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1506368249639-73a05d6f6488?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"7. การนึ่ง (Steam)","desc":"ใช้ไอน้ำจากน้ำเดือดในหม้อนึ่ง/ลังถึง วางอาหารชั้นบนปิดฝาให้สนิท สารอาหารไม่สัมผัสน้ำโดยตรง จึง \"สงวนคุณค่าทางอาหารได้ดีกว่าการต้ม\"","image":"[https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"8. การตุ๋น (Simmer / Double Boiler)","desc":"มักใช้หม้อ 2 ชั้นซ้อนกัน ใช้ไฟอ่อน อาหารจะสุกนุ่มละลายในปาก ปราศจากเชื้อโรค เหมาะสำหรับเด็กทารก ผู้ป่วย ผู้สูงอายุ (ข้อเสีย: ใช้เวลาปรุงนาน)","image":"[https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=600&q=80&fm=webp)"}]}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'เทคนิคการประกอบอาหารด้วยของเหลว / ความร้อนชื้น', 'การต้ม ลวก นึ่ง ตุ๋น (Moist Heat Cooking Methods)', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 11: methods
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 11, 11, 'methods', NULL, '{"items":[{"name":"9. การผัด (Stir-Frying)","desc":"ใช้น้ำมันเล็กน้อย ใช้ไฟแรง นำเนื้อหรือผักลงกระทะ ใช้ตะหลิวคนกลับไปมาในระยะเวลาสั้นๆ ปริมาณไขมันน้อยกว่าทอด (ข้อเสีย: ถ้านานไปสีจะไม่สวย)","image":"[https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"10. การทอด (Frying)","desc":"นำอาหารลงไปทอดในน้ำมันร้อนๆ ปริมาณมาก ควรทอดด้านหนึ่งให้สุกก่อนค่อยกลับด้าน อาหารมีกลิ่นหอม สีสวย กรอบ (ข้อเสีย: อมไขมันสูง)","image":"[https://images.unsplash.com/photo-1569691899455-88464f6d3ab1?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1569691899455-88464f6d3ab1?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"เพิ่มเติม 1: การเจียว","desc":"ทำอาหารให้สุกในน้ำมันโดย \"ใช้ไฟอ่อน\" วัตถุดิบมักถูกซอยละเอียด ใส่ตอนน้ำมันยังไม่ร้อนจัด เจียวจนเหลืองกรอบ เช่น กระเทียมเจียว","image":"[https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=600&q=80&fm=webp)"},{"name":"เพิ่มเติม 2: การคั่ว และ การรวน","desc":"คั่ว: \"ไม่ใช้น้ำมัน\" ใส่ภาชนะแห้ง ใช้ไฟอ่อนคนตลอดจนหอมกรอบ | รวน: คล้ายคั่วแต่ \"ใส่น้ำมันเล็กน้อย\" ปรุงรสเค็ม เพื่อถนอมเนื้อสัตว์","image":"[https://images.unsplash.com/photo-1558222218-b7b54eede3f3?auto=format&fit=crop&w=600&q=80&fm=webp](https://images.unsplash.com/photo-1558222218-b7b54eede3f3?auto=format&fit=crop&w=600&q=80&fm=webp)"}]}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'เทคนิคการประกอบอาหารด้วยน้ำมัน', 'การผัด ทอด เจียว คั่ว รวน (Fat-Based Cooking)', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

-- Page 12: quiz-interactive
WITH module_ref AS (
  SELECT m.id AS module_id FROM course_modules m
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND m.slug = 'main'
), inserted_page AS (
  INSERT INTO lesson_pages (module_id, sort_order, legacy_page_id, page_type, quiz_mode, content)
  SELECT module_id, 12, 12, 'quiz_interactive', 'post', '{"pass_threshold":0.6}'::jsonb FROM module_ref
  ON CONFLICT (module_id, sort_order) DO UPDATE SET legacy_page_id = EXCLUDED.legacy_page_id, page_type = EXCLUDED.page_type, quiz_mode = EXCLUDED.quiz_mode, content = EXCLUDED.content
  RETURNING id
)
INSERT INTO page_translations (page_id, locale, title, subtitle, body)
  SELECT id, 'th', 'แบบทดสอบประเมินความรู้ (Post-Test)', 'ทดสอบความเข้าใจหลังการเรียนการสอน จำนวน 10 ข้อ', '{}'::jsonb FROM inserted_page
  ON CONFLICT (page_id, locale) DO UPDATE SET title = EXCLUDED.title, subtitle = EXCLUDED.subtitle;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 1, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'ข้อใดคือความหมายที่ครบถ้วนที่สุดของ ''การประกอบอาหาร''?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 1
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การใช้ความร้อนทำให้อาหารสุกและมีสีสันสวยงาม' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 1
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การทำอาหารดิบให้สุกด้วยความร้อน เพื่อความเหมาะสม ปลอดภัย และมีคุณค่า' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 1
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การหั่นเตรียมวัตถุดิบและจัดจานให้สวยงาม' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 1
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การถนอมอาหารเพื่อยืดอายุการเก็บรักษาให้นานที่สุด' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 2, 2 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'วิตามินชนิดใดที่มักจะสูญเสียไปได้ง่ายที่สุดในขั้นตอนการประกอบอาหารแบบต้มทิ้ง?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 2
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'วิตามิน A และ D' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 2
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'วิตามิน E และ K' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 2
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'วิตามิน B และ C' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 2
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'แคลเซียม และ ธาตุเหล็ก' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 3, 3 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'ข้อใดคือลักษณะงานหลักที่อยู่ในความรับผิดชอบของ ''ครัวเย็น (Cold Kitchen)''?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 3
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การอบขนมปังและทำเค้ก' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 3
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การเคี่ยวน้ำสต็อกและทำน้ำซุป' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 3
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การทอดอาหารและทำอาหารเช้า' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 3
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การทำสลัด อาหารเรียกน้ำย่อย และหั่นเนื้อ Cold cut' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 4, 0 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'แผนก ''Soup & Stock'' มักจะถูกจัดให้อยู่ในครัวประเภทใด?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 4
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวร้อน (Hot Kitchen)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 4
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวเย็น (Cold Kitchen)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 4
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ครัวเบเกอรี่ (Bakery Kitchen)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 4
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'แผนกจัดเลี้ยง (Banquet)' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 5, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'ข้อใดคือวิธีการประกอบอาหารด้วย ''ความร้อนแห้ง (Dry Heat)'' ทั้งหมด?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 5
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ต้ม, ลวก, นึ่ง, ตุ๋น' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 5
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ปิ้ง, ย่าง, เผา, อบ' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 5
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ผัด, ทอด, เจียว, รวน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 5
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'อบ, นึ่ง, ผัด, ต้ม' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 6, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'ตามทฤษฎีการประกอบอาหาร ก่อนนำไก่เข้า ''อบ (Bake)'' ควรทำสิ่งใดก่อนเป็นอันดับแรก?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 6
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'นำไก่ไปต้มให้สุกครึ่งหนึ่ง' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 6
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'อุ่นเตาอบให้ร้อนล่วงหน้าประมาณ 15 นาที (Pre-heat)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 6
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'นำไก่ไปแช่แข็งเพื่อให้หนังกรอบ' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 6
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ราดน้ำเย็นจัดลงบนตัวไก่' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 7, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'เทคนิคการประกอบอาหารแบบใด ที่ช่วยสงวนคุณค่าทางอาหารได้ดีที่สุดเพราะสารอาหารไม่ละลายน้ำ?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 7
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การต้ม (Boil)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 7
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การนึ่ง (Steam)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 7
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การตุ๋น (Simmer)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 7
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การลวก (Blanch)' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 8, 2 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'การนำผักลงไปต้มในน้ำเดือดจัดระยะสั้นๆ แล้วรีบตักขึ้น ''แช่น้ำเย็นจัดทันที'' คือเทคนิคใด?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 8
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การต้ม (Boil)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 8
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การนึ่ง (Steam)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 8
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การลวก (Blanch)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 8
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การตุ๋น (Simmer)' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 9, 2 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'ข้อใดคือความแตกต่างระหว่าง ''การคั่ว'' และ ''การรวน''?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 9
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การคั่วใช้ไฟแรงมาก ส่วนการรวนใช้ไฟอ่อน' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 9
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การคั่วทำในเตาอบ ส่วนการรวนทำในกระทะ' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 9
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การคั่วไม่ใช้น้ำมันเลย ส่วนการรวนจะใส่น้ำมันเล็กน้อยและปรุงรสเค็ม' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 9
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'ไม่มีความแตกต่าง เป็นคำเรียกที่ใช้แทนกันได้' FROM inserted_o;

WITH page_ref AS (
  SELECT lp.id AS page_id FROM lesson_pages lp
  JOIN course_modules m ON lp.module_id = m.id
  JOIN courses c ON m.course_id = c.id
  JOIN organizations o ON c.org_id = o.id
  WHERE o.slug = 'default-org' AND c.slug = 'cooking-basics' AND lp.legacy_page_id = 12 AND lp.sort_order = 12
), inserted_q AS (
  INSERT INTO quiz_questions (page_id, sort_order, correct_option_index)
  SELECT page_id, 10, 1 FROM page_ref
  RETURNING id, page_id
)
INSERT INTO quiz_question_translations (question_id, locale, prompt, hint, image_url, image_alt)
  SELECT id, 'th', 'การประกอบอาหารวิธีใด ที่เหมาะสำหรับเด็กทารกและผู้ป่วย เพราะอาหารสุกนุ่มเปื่อยที่สุด?', NULL, NULL, NULL FROM inserted_q;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 10
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 1 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การย่าง (Roast)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 10
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 2 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การตุ๋น (Simmer ด้วยหม้อ 2 ชั้น)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 10
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 3 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การผัด (Stir-Frying)' FROM inserted_o;
WITH q_ref AS (
  SELECT qq.id AS question_id FROM quiz_questions qq
  JOIN lesson_pages lp ON qq.page_id = lp.id
  WHERE lp.legacy_page_id = 12 AND qq.sort_order = 10
), inserted_o AS (
  INSERT INTO quiz_options (question_id, sort_order)
  SELECT question_id, 4 FROM q_ref RETURNING id
)
INSERT INTO quiz_option_translations (option_id, locale, label)
  SELECT id, 'th', 'การเผา (Burn)' FROM inserted_o;

COMMIT;
